version: '3'

services:
  db:
    image: mysql:8.0
    container_name: wsol-mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-WSOL}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/WSOL.sql:/docker-entrypoint-initdb.d/WSOL.sql
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  mysql-data:
