FROM node:18-alpine

WORKDIR /app

# ติดตั้ง dependencies ก่อน เพื่อใช้ประโยชน์จาก Docker cache
COPY package.json package-lock.json* ./
RUN npm install

# คัดลอกโปรเจคทั้งหมด
COPY . .

# สำหรับการพัฒนา เราจะรัน Next.js ในโหมด development
CMD ["npm", "run", "dev"]

# Expose port 3000
EXPOSE 3000
